### ISSUE TITLE
Once user logs in, display the rootVC as the app opens (not the login page)

### ISSUE THREAD

**Issue by harumhl** [harumhl/Showcase#19]

**Comment by harumhl** [comment]
How to set it up: https://stackoverflow.com/questions/32005900/show-another-view-controller-at-the-first-launch-and-not-again

I don't know how the log in info is stored, but that's all that'll need for the condition

**Comment by ifroob** [comment]
Fixed: If a user is authenticated and closes the application, they will be automatically segued to the RootVC once they open the application again.
