### ISSUE TITLE
constraints on labels in PostScanVC

### ISSUE THREAD

**Issue by harumhl** [harumhl/Showcase#20]
We should handle the case where the book title is too long and such

**Comment by ellisbrandon20** [comment]
Right now I have it to where everthing gets pushed downward. I am not sure what you mean by your comment. What do you think it should look like when it is "too long" (whatever is defined as too long)

**Comment by harumhl** [comment]
In a smaller phone, the title can be too long to cover up the author's name and other info. So after a certain number of characters, we can cut it off and leave it with "..."
