### ISSUE TITLE
Display Store Name in PostScanVC

### ISSUE THREAD

**Issue by ellisbrandon20** [harumhl/Showcase#3]

**Comment by ifroob** [comment]
Now that store name gets passed through, I display it on the Nav Bar.  If we're segueing from History, it won't have know what the store name is.  We will need to write it to the DB and then read it or something.

**Comment by ifroob** [comment]
Fixed this now in the latest commit.  History reads the store name from the database.

**Comment by ellisbrandon20** [comment]
Place the Store Name above the purchase button.. If the store name is not "valid" then hide the purchase button and dont run the functions that generate the PurchaseURL

**Comment by harumhl** [comment]
Also display whether the store participates in the Amazon affiliate service
