### ISSUE TITLE
user account

### ISSUE THREAD

**Issue by ellisbrandon20** [harumhl/Showcase#6]
give users the ability to change their log in information if used the app log in not FB

**Comment by GuillermoLopezJr** [comment]
update password
update email
facebook login wont be able to update the two fields above (should be hidden)
two different log outs. one for facebook and one for regular email log on

**Comment by GuillermoLopezJr** [comment]
I am currently working on this.

Brian and I worked on this. Chasing email was too much trouble. We had to make major changes to our database.
